In [2]:
# Import libraries

import cv2
import numpy as np

In [17]:
a = cv2.imread('images/fig5.png')
a = np.float64(a)

In [18]:
print(a.shape)

(466, 700, 3)


In [19]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)

(2, 3)


In [66]:
print("First Shape:", a[0].shape)
print("First X:", a[0].shape[0])
print("First Y:", a[0].shape[1])
print("======================")
print("First Ten Arrays:\n", a[0, 0:10])
print("======================")
print("Last Ten Arrays:\n", a[0, -10:])
print("======================")
print(a[0, 1, 0])
print(a[0, 1, 1])
print(a[0, 1, 2])
print(a[0])

First Shape: (700, 3)
First X: 700
First Y: 3
First Ten Arrays:
 [[ 103.   61.   24.]
 [ 105.   63.   28.]
 [ 106.   64.   29.]
 [ 108.   63.   30.]
 [ 110.   65.   32.]
 [ 110.   65.   31.]
 [ 110.   65.   31.]
 [ 112.   68.   31.]
 [ 113.   68.   31.]
 [ 113.   68.   31.]]
Last Ten Arrays:
 [[ 233.  221.  211.]
 [ 233.  221.  211.]
 [ 232.  220.  208.]
 [ 231.  219.  207.]
 [ 229.  217.  205.]
 [ 228.  216.  204.]
 [ 232.  217.  201.]
 [ 231.  216.  200.]
 [ 229.  214.  198.]
 [ 227.  212.  196.]]
105.0
63.0
28.0
[[ 103.   61.   24.]
 [ 105.   63.   28.]
 [ 106.   64.   29.]
 ..., 
 [ 231.  216.  200.]
 [ 229.  214.  198.]
 [ 227.  212.  196.]]


In [21]:
print("Height of Image is", int(a.shape[0]), "pixels")

Height of Image: 466 pixels


In [24]:
print("Width of Image os", int(a.shape[1]), "pixels")

Width of Image os 700 pixels
