In [105]:
# Import libraries

import cv2
import numpy as np
from matplotlib import pyplot as plt

In [93]:
a = cv2.imread('images/fig5.png')

In [94]:
print(a.shape)

(466, 700, 3)


In [95]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)

(2, 3)


In [96]:
print("First Shape:", a[0].shape)
print("First X:", a[0].shape[0])
print("First Y:", a[0].shape[1])
print("======================")
print("First Ten Arrays:\n", a[0, 0:10])
print("======================")
print("Last Ten Arrays:\n", a[0, -10:])
print("======================")
print(a[0, 1, 0])
print(a[0, 1, 1])
print(a[0, 1, 2])
print(a[0])

First Shape: (700, 3)
First X: 700
First Y: 3
First Ten Arrays:
 [[103  61  24]
 [105  63  28]
 [106  64  29]
 [108  63  30]
 [110  65  32]
 [110  65  31]
 [110  65  31]
 [112  68  31]
 [113  68  31]
 [113  68  31]]
Last Ten Arrays:
 [[233 221 211]
 [233 221 211]
 [232 220 208]
 [231 219 207]
 [229 217 205]
 [228 216 204]
 [232 217 201]
 [231 216 200]
 [229 214 198]
 [227 212 196]]
105
63
28
[[103  61  24]
 [105  63  28]
 [106  64  29]
 ..., 
 [231 216 200]
 [229 214 198]
 [227 212 196]]


In [97]:
print("Height of Image is", int(a.shape[0]), "pixels")

Height of Image is 466 pixels


In [98]:
print("Width of Image os", int(a.shape[1]), "pixels")

Width of Image os 700 pixels


In [99]:
print(a[0, :10, 0], a[0, :10, 1])

[103 105 106 108 110 110 110 112 113 113] [61 63 64 63 65 65 65 68 68 68]


In [104]:
sobel_x = cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5)
sobel_y = cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)

In [107]:
print(a[0])

[[103  61  24]
 [105  63  28]
 [106  64  29]
 ..., 
 [231 216 200]
 [229 214 198]
 [227 212 196]]


In [108]:
print(sobel_x[0])

[[   0.    0.    0.]
 [ 150.   82.  178.]
 [ 214.   68.  180.]
 ..., 
 [-122. -152. -210.]
 [-146. -146. -146.]
 [   0.    0.    0.]]
