In [2]:
# Import libraries

import cv2
import numpy as np

In [17]:
a = cv2.imread('images/fig5.png')
a = np.float64(a)

In [18]:
print(a.shape)

(466, 700, 3)


In [19]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print(array.shape)

(2, 3)


In [16]:
print(a[0].shape)
print(a[0])

[ 700.    3.]
[[103  61  24]
 [105  63  28]
 [106  64  29]
 ..., 
 [231 216 200]
 [229 214 198]
 [227 212 196]]
